# Generated by Django 5.2.5 on 2025-11-20 12:57

import custom_components.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('Mail2PDF Agent', 'Mail2PDF Agent')], max_length=500)),
                ('agent_description', models.TextField(blank=True, null=True)),
                ('agent_config_schema', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cron_timing', models.CharField(help_text="CRON expression like '0 0 * * *' for daily at midnight", max_length=500)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_schema_json', models.JSONField(blank=True, null=True)),
                ('bot_element_permission', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard_types', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard_config', models.JSONField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dms_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_types', models.CharField(choices=[('Google Drive', 'Google Drive'), ('S3 Bucket', 'S3 Bucket'), ('One Drive', 'One Drive'), ('SFTP Storage', 'SFTP Storage')], default='Google Drive', max_length=100)),
                ('config_details_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dms_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=500, null=True)),
                ('folder_id', models.CharField(blank=True, max_length=500, null=True)),
                ('download_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_id', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Integration_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('integration_type', models.CharField(choices=[('api', 'api')], default='api', max_length=100)),
                ('integration_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('integration_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationBotSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notify', 'Notify'), ('approve', 'Approve')], max_length=20)),
                ('notification_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_name', models.CharField(max_length=255)),
                ('notification_field_id', models.CharField(max_length=255)),
                ('receiver_type', models.CharField(choices=[('field_ref', 'Field Reference'), ('value', 'Value')], max_length=20)),
                ('receiver_mail', models.JSONField(blank=True, null=True)),
                ('mail_content', models.JSONField(blank=True, null=True)),
                ('notification_element_permission', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('mail_token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mail_data', models.JSONField(blank=True, null=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('approved_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('ocr_type', models.CharField(choices=[('Aadhar Card Extraction', 'Aadhar Card Extraction'), ('Pan Card Extraction', 'Pan Card Extraction'), ('PDF Extraction', 'PDF Extraction'), ('QR Extraction', 'QR Extraction'), ('Invoice Extraction', 'Invoice Extraction')], default='Aadhar Card Extraction', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocr_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('data_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_code', models.CharField(max_length=5, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('org_description', models.TextField(blank=True, null=True)),
                ('large_logo_url', models.URLField(blank=True, null=True)),
                ('small_logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=10, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=10, null=True)),
                ('accent1_color', models.CharField(blank=True, max_length=10, null=True)),
                ('accent2_color', models.CharField(blank=True, max_length=10, null=True)),
                ('accent3_color', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_set_password', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('process', 'Process'), ('form', 'Form'), ('subprocess', 'Subprocess'), ('core data', 'Core Data')], max_length=50)),
                ('data_id', models.PositiveIntegerField()),
                ('query', models.JSONField(blank=True, null=True)),
                ('query_result', models.JSONField(blank=True, null=True)),
                ('user_groups', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_schema', models.JSONField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduler_name', models.CharField(choices=[('email spooling ', 'email spooling'), ('PDFSpooler', 'PDFSpooler')], max_length=255)),
                ('frequency', models.CharField(max_length=100)),
                ('scheduler_config', models.JSONField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_description', models.TextField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bot_name', models.CharField(choices=[('google_drive', 'google_drive'), ('email', 'email'), ('screen_scraping', 'screen_scraping'), ('file_extractor', 'file_extractor'), ('PDF Generator', 'PDF Generator'), ('Doc Builder', 'Doc Builder'), ('Doc Generator', 'Doc Generator'), ('Desktop Automation', 'Desktop Automation'), ('QR Generator', 'QR Generator'), ('Prompt Bot', 'Prompt Bot')], default='google_drive', max_length=100)),
                ('bot_description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['bot_uid'], name='custom_comp_bot_uid_a60dfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_schema', models.JSONField(blank=True, null=True)),
                ('temp_data', models.FileField(blank=True, null=True, upload_to=custom_components.models.user_directory_path)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot')),
            ],
        ),
    ]
