# Generated by Django 4.2.7 on 2025-11-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0002_createprocess_created_on_createprocess_updated_on'),
        ('custom_components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_bot_data', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_data', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_bot_data', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='botschema',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot'),
        ),
        migrations.AddField(
            model_name='botschema',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_bot_schema', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='botschema',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_schema', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_dashboard', to='custom_components.usergroup'),
        ),
        migrations.AddField(
            model_name='dms',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_dms', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='dms',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_dms_data', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='dms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms_dms_data', to='custom_components.dms'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms_data', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_dms_data', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='form_generator.userdata'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_dms_data', to='custom_components.usergroup'),
        ),
        migrations.AddField(
            model_name='integration',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_integration_schema', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_schema', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_integration_details', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='integration_details', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='integration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_components.integration'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_integration_details', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='notificationbotschema',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiifcationbot', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='notificationbotschema',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_notificationbot', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_notification_data', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiifcationdata', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_notificationdata', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='ocr',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_ocr', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='ocr',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='ocr_details',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_ocr_details', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='ocr_details',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='process_ocr_details', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='ocr_details',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_details', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot'),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportConfig', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_scheduler', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='schedulerdata',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_scheduler_data', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='schedulerdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedulerdata', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='schedulerdata',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_schedulerdata', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='schedulerdata',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='custom_components.scheduler'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='custom_components.organization'),
        ),
        migrations.AddIndex(
            model_name='botschema',
            index=models.Index(fields=['bot'], name='custom_comp_bot_id_742e47_idx'),
        ),
        migrations.AddIndex(
            model_name='botschema',
            index=models.Index(fields=['organization'], name='custom_comp_organiz_15f349_idx'),
        ),
        migrations.AddIndex(
            model_name='botschema',
            index=models.Index(fields=['flow_id'], name='custom_comp_flow_id_f16f45_idx'),
        ),
        migrations.AddIndex(
            model_name='botschema',
            index=models.Index(fields=['organization', 'bot'], name='custom_comp_organiz_89fb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='botschema',
            index=models.Index(fields=['organization', 'flow_id'], name='custom_comp_organiz_912e71_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbotschema',
            index=models.Index(fields=['notification_uid'], name='custom_comp_notific_2e3763_idx'),
        ),
    ]
