# Generated by Django 5.2.5 on 2025-11-20 12:57

import datetime
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(blank=True, max_length=200)),
                ('Instance_IP', models.CharField(blank=True, max_length=200)),
                ('Instance_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Email', 'Email'), ('In-App', 'In-App')], max_length=20)),
                ('notification_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('notification_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, max_length=200)),
                ('process_description', models.CharField(blank=True, max_length=700, null=True)),
                ('initiator_group', models.IntegerField(blank=True, null=True)),
                ('first_step', models.CharField(blank=True, max_length=255, null=True)),
                ('participants', models.JSONField(blank=True, null=True)),
                ('subprocess_UID', models.CharField(blank=True, max_length=50)),
                ('process_stages', models.JSONField(blank=True, null=True)),
                ('process_table_configuration', models.JSONField(blank=True, null=True)),
                ('parent_case_data_schema', models.JSONField(blank=True, default=list, null=True)),
                ('process_table_permission', models.JSONField(blank=True, default=list, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('dms', models.ManyToManyField(blank=True, related_name='dms', to='custom_components.dms')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_process', to='custom_components.organization')),
                ('parent_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocesses', to='form_generator.createprocess')),
                ('user_group', models.ManyToManyField(blank=True, related_name='usergroup_create_process', to='custom_components.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(max_length=500)),
                ('stages', models.CharField(blank=True, max_length=500)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=300)),
                ('next_step', models.CharField(blank=True, max_length=200)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('path_json', models.JSONField(blank=True, default=list, null=True)),
                ('user_case_history', models.JSONField(blank=True, default=list, null=True)),
                ('parent_case_data', models.JSONField(blank=True, null=True)),
                ('case_data_comments', models.JSONField(blank=True, default=list, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='custom_components.organization')),
                ('parent_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cases', to='form_generator.case')),
                ('current_subprocess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprocess_cases', to='form_generator.createprocess')),
                ('processId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='EndElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(blank=True, max_length=200, null=True)),
                ('element_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('end_element_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endElement', to='custom_components.organization')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='FormDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_uid', models.CharField(blank=True, max_length=500)),
                ('form_description', models.CharField(blank=True, max_length=500)),
                ('form_name', models.CharField(blank=True, max_length=200)),
                ('form_json_schema', models.JSONField(blank=True, null=True)),
                ('form_style_schema', models.JSONField(blank=True, null=True)),
                ('form_status', models.BooleanField(default=False)),
                ('form_created_by', models.CharField(blank=True, default='admin', max_length=200)),
                ('form_created_on', models.DateField(default=datetime.date.today)),
                ('core_table', models.BooleanField(default=False)),
                ('form_filter_schema', models.JSONField(blank=True, null=True)),
                ('form_send_mail', models.BooleanField(default=False)),
                ('form_send_mail_schema', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_info', to='custom_components.organization')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='FormPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.formdatainfo')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_permission', to='custom_components.usergroup')),
            ],
        ),
        migrations.AddField(
            model_name='formdatainfo',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='usergroup_form_data_info', through='form_generator.FormPermission', to='custom_components.usergroup'),
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_details', models.JSONField()),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='custom_components.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDismiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.case')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.notification')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleId', models.CharField(blank=True, max_length=200)),
                ('rule_type', models.CharField(blank=True, max_length=200)),
                ('rule_json_schema', models.JSONField(blank=True, null=True)),
                ('form_rule_schema', models.JSONField(blank=True, null=True)),
                ('process_codeblock_schema', models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_generator.formdatainfo')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='custom_components.organization')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=50)),
                ('access_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('counter', models.IntegerField(default=1)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='custom_components.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaId', models.CharField(blank=True, max_length=200)),
                ('sla_json_schema', models.JSONField(blank=True, null=True)),
                ('caseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.case')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('mail_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('is_lead', models.BooleanField(blank=True, default=False, null=True)),
                ('user_profile_schema', models.JSONField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='custom_components.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_user_data', to='custom_components.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='FilledFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formId', models.CharField(blank=True, max_length=200)),
                ('data_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=500, null=True)),
                ('core_filled_data', models.BooleanField(blank=True, default=False, null=True)),
                ('is_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('caseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.case')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_data', to='custom_components.organization')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
                ('user_groups', models.ManyToManyField(blank=True, related_name='usergroup_filled_form_data', to='custom_components.usergroup')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='cases', to='form_generator.userdata'),
        ),
        migrations.CreateModel(
            name='UserFormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_form_schema', models.JSONField()),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_form_schema', to='custom_components.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='createprocess',
            index=models.Index(fields=['organization'], name='form_genera_organiz_d9266b_idx'),
        ),
        migrations.AddIndex(
            model_name='createprocess',
            index=models.Index(fields=['subprocess_UID'], name='form_genera_subproc_3390f7_idx'),
        ),
        migrations.AddIndex(
            model_name='createprocess',
            index=models.Index(fields=['organization', 'subprocess_UID'], name='form_genera_organiz_45d44e_idx'),
        ),
        migrations.AddIndex(
            model_name='endelement',
            index=models.Index(fields=['organization'], name='form_genera_organiz_5f0bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='endelement',
            index=models.Index(fields=['element_uid'], name='form_genera_element_8d737e_idx'),
        ),
        migrations.AddIndex(
            model_name='endelement',
            index=models.Index(fields=['process'], name='form_genera_process_e5cc66_idx'),
        ),
        migrations.AddIndex(
            model_name='endelement',
            index=models.Index(fields=['organization', 'element_uid'], name='form_genera_organiz_753386_idx'),
        ),
        migrations.AddIndex(
            model_name='endelement',
            index=models.Index(fields=['organization', 'process'], name='form_genera_organiz_2c9576_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formpermission',
            unique_together={('user_group', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationdismiss',
            unique_together={('user', 'notification', 'process', 'case')},
        ),
        migrations.AddIndex(
            model_name='filledformdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data_json'], name='form_genera_data_js_6434ed_gin'),
        ),
        migrations.AddIndex(
            model_name='filledformdata',
            index=models.Index(fields=['organization'], name='form_genera_organiz_1ca1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='filledformdata',
            index=models.Index(fields=['processId'], name='form_genera_process_88689d_idx'),
        ),
        migrations.AddIndex(
            model_name='filledformdata',
            index=models.Index(fields=['caseId'], name='form_genera_caseId__9abd08_idx'),
        ),
        migrations.AddIndex(
            model_name='filledformdata',
            index=models.Index(fields=['updated_at'], name='form_genera_updated_f5168b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization'], name='form_genera_organiz_2c1440_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['processId'], name='form_genera_process_dae159_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='form_genera_status_281910_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['stages'], name='form_genera_stages_c05deb_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['id'], name='form_genera_id_2a5da8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'status'], name='form_genera_organiz_8622b0_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'stages'], name='form_genera_organiz_0ff362_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'processId'], name='form_genera_organiz_110b53_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'created_on'], name='form_genera_organiz_e6db34_idx'),
        ),
    ]
