# Generated by Django 4.2.7 on 2025-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprocess',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='createprocess',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
