# Generated by Django 5.2.5 on 2025-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaCaseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SlaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_name', models.CharField(blank=True, max_length=300)),
                ('sla_uid', models.CharField(blank=True, max_length=300)),
                ('sla_json_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
