# Generated by Django 4.2.7 on 2025-11-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0002_agent_organization_botdata_case_id_botdata_flow_id_and_more'),
        ('form_generator', '0002_createprocess_created_on_createprocess_updated_on'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slacaseinstance',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_instance', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='slacaseinstance',
            name='sla_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_instance', to='automation.slaconfig'),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_org', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='process_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_process', to='form_generator.createprocess'),
        ),
    ]
